### ISSUE TITLE
Reduce karma threshold for posting a thread from 10 to 5

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#21]
This appears to be set in the code.

**Comment by tog22** [comment]
@alexflint do you want to have a go at this?

**Comment by peterhurford** [comment]
This should be useful: https://github.com/tricycle/eaforum/search?utf8=%E2%9C%93&q=karma_to_post&type=Code

**Comment by arichard4** [comment]
FYI, development.ini is in the .gitignore

Also, is this change aimed specifically at me?

**Comment by arichard4** [comment]
Since development.ini is in the .gitignore, it will need to be edited manually by Trike. (Or, if they have it on vagrant, regenerated from its template.) (Or, we could remove it from the .gitignore temporarily.) I've changed the template for development.ini to generate it with the reduced karma threshold.

**Comment by tog22** [comment]
I've talked to Trike (the people who administer the live site) a bit so I'll ask them to do that. ( @peterhurford, as it's not a typical PR, I've got getting this to Trike covered.)

**Comment by peterhurford** [comment]
Submitted to Trike as https://github.com/tricycle/eaforum/pull/11
