### ISSUE TITLE
Change error message

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#30]
Currently an error in the code yield this message:

> You have encountered an error in the code that runs Less Wrong. The site maintainers have been informed and will get to it is as soon as they can.
> 
> In the unlikely event that you've bumped into this error before and think that no-one is paying attention, please report the error and how to reproduce it on http://code.google.com/p/lesswrong/issues/list'
> 
> If the error is localised you might still find awesome Less Wrong content in the Main article area or in the Discussion area.

We should change this, including asking people to report errors at https://github.com/tog22/eaforum/issues

**Comment by arichard4** [comment]
This is appears to be located in eaforum/r2/r2/i18n/en/LC_MESSAGES- at least; that and the build folder appear to be the only occurrences of that text, per grep.

I'm not able to test the changes, because I've never been able to get the meetups working at all- trying to add one on my local version of the EA Forum causes an error: ''DefTemplate' object has no attribute 'uri' ' Is there another good way to look at the error page?

This is also a slow fix for trike, because I'm pretty sure it will require rebuilding.

**Comment by arichard4** [comment]
Testing this requires changing debug= true in development.ini to debug=false, then breaking the site.

This made a _whole lot_ of changes, and I'm going to try to see what method Trike used to compile the .po files to see if I can make fewer. Essentially, most strings are specified in eaforum/r2/r2/i18n/en/LC_MESSAGES/r2.po; this file is then compiled to eaforum/r2/r2/i18n/en/LC_MESSAGES/r2.mo. Trike did change the error message in r2.po: 

https://github.com/tricycle/eaforum/commit/97aa3aaad8ae885b79f1e80f89395fe138a32fde

But they never compiled the change to r2.mo. I added a link to the issues page and compiled it to r2.mo using poedit; this produced a very large number of substanceless changes, to do with poedit's save format, which is different from the one Trike/reddit uses. Testing shows that everything still seems to work fine, but also my testing has not been reliable thus far (c.f. issue 35).

**Comment by tog22** [comment]
Hmm, that is a lot of changes, how confident are you that none are (significantly) problematic? If you're confident there are probably more valuable things you can do than reducing the number of changes. :) Can @peterhurford and I submit a PR with this commit?

**Comment by arichard4** [comment]
Not confident at all, I have no idea what's going on behind the scenes in r2.mo and will keep looking for reddit's .po->.mo compilation method. (I can't do it manually- that broke the error message such that it displayed the message id instead of the actual message.)

Can you merge this into master but not submit a PR to trike? This isn't at all an urgent issue, so we can build future stuff on top of it and let it fall under their testing. It's an added possible complication, but I'm pretty sure this will be OK and if it fails it will be in an obvious way (i.e. text getting messed up).

**Comment by arichard4** [comment]
Right, got it down to only the necessary changes

**Comment by tog22** [comment]
Awesome! Over to you to handle the PR @peterhurford

**Comment by peterhurford** [comment]
Submitted to Trike as https://github.com/tricycle/eaforum/pull/17

**Comment by arichard4** [comment]
tricycle#17 was the .po file, but not the .mo file, so production isn't currently showing the changes (The .po file is compiled to the .mo binary, which various parts of the code draw text from)

**Comment by peterhurford** [comment]
@arichard4 How do you compile the .mo from the .po?

Can you submit a PR to tricycle/eaforum directly from your personal fork and then mention it in the issue?  (That's how we're doing it now.)

**Comment by tog22** [comment]
Or submit if from a branch on this community development  fork, and mention
the issue in the commit message, up to you.

**Comment by arichard4** [comment]
I pushed the compiled/binary .mo here, as part of this commit:
https://github.com/tog22/eaforum/commit/d3ed6397d4b64e79e5237f6a6476063d8352254f

I'll submit a PR today.

**Comment by patbl** [comment]
It looks as though @peterhurford merged a fix. (The only difference I see is the capitalization of "main.")

**Comment by patbl** [comment]
Oh, I didn't read the bit about mo and po files. Mo files, mo problems.

**Comment by tog22** [comment]
:heart:

**Comment by peterhurford** [comment]
PR was merged by Trike.
