### ISSUE TITLE
Clarify and/or improve post formatting UI

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#57]
> There were different text styles (Paragraph, Formatted, Headers, etc.), but it wasn't clear what any of them meant, and there didn't seem to be a Plaintext option (to remove all formatting and start over when things get wonky). 
> 
> I was having difficulties with spacing. E.g., in the current post, there are large spaces between the headers and bulleted lists, even when that didn't show up in my edit window.
> 
> I think there weren't options for font or text size (or both?), yet changing text styles, typing new text into the window, or copying over text of certain font/size from the gdoc changed the way the text looked. 
> 
> I couldn't choose to center anything.
> 
> Dealing with images is weird - couldn't upload them from my computer; just had to copy and paste from the gdoc. I wished I could select them and put an outline on them, because the two images with white backgrounds are hard to tell apart. 
> 
> The draft posts I saved to my own account looked different from how the post appeared when I published it to the Forum.

**Comment by patbl** [comment]
We're using a version of TinyMCE that's from 2008: https://github.com/patbl/eaforum/blob/master/r2/r2/public/static/tiny_mce/tiny_mce_src.js#L7

We could see whether upgrading to a more-recent version helps.

If upgrading is a hassle, it might be worthwhile to switch to something better. Ozzie recommends [Draft JS](https://facebook.github.io/draft-js/) (very flexible; depends on React) or [Summernote](http://summernote.org/) (batteries included).

**Comment by tog22** [comment]
TinyMCE also has a 'paste as plain text' and 'paste from Word' button,
which are both intended to prevent inappropriate <style>s being pasted in,
though it'd be worth checking whether the latter is reliable enough to
include. We're writing a guide on avoiding inappropriate <style>s being
pasted in which we're adding to the FAQ, and would update this.

**Comment by patbl** [comment]
> There were different text styles (Paragraph, Formatted, Headers, etc.), but it wasn't clear what any of them meant, and there didn't seem to be a Plaintext option (to remove all formatting and start over when things get wonky).

tricycle/eaforum#47 adds a "remove formatting" button.

> I was having difficulties with spacing. E.g., in the current post, there are large spaces between the headers and bulleted lists, even when that didn't show up in my edit window.

This seems a pretty common problem in rich-text editors. I've encountered it not infrequently on Gmail. I don't think there's much we can do about it, other than adding a "remove formatting" button.

> I think there weren't options for font or text size (or both?), yet changing text styles, typing new text into the window, or copying over text of certain font/size from the gdoc changed the way the text looked.

I'm not sure we'd want to have such options available through the UI. The website would come across as more professional if the formatting were consistent. Would making it easier to format text in these ways lead to more or less consistency? The answer would depend in part on how many articles are pasted as opposed to typed into the editor directly.

tricycle/eaforum#47 adds alignment options in the drop-down menu.

> Dealing with images is weird - couldn't upload them from my computer; just had to copy and paste from the gdoc. I wished I could select them and put an outline on them, because the two images with white backgrounds are hard to tell apart.

Image uploads are broken: #68. It looks as though it would be easy to allow [adding image borders](http://www.devsumo.com/technotes/2014/07/tinymce-4-dude-wheres-my-border/) in TinyMCE, though I doubt whether many people would use the option.

> The draft posts I saved to my own account looked different from how the post appeared when I published it to the Forum.

This could be because, as I understand it, only styles from a single style sheet are applied in the editing textarea: https://github.com/tricycle/eaforum/blob/0248315daec927f27be1d47c9e909f7c3a7aff86/r2/r2/public/static/tinymce.js#L7

If that's the problem, I don't know of an easy solution. If we concatenated all our style sheets into a single one, we could point TinyMCE to that, but I don't think we do.

**Comment by patbl** [comment]
Some of these problems were fixed in https://github.com/tricycle/eaforum/pull/47. There's a separate issue for image uploads. Other bugs and feature requests can go in separate issues.
