### ISSUE TITLE
Should MIRI be on the list of blogs?

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#72]
...CFAR is.

**Comment by patbl** [comment]
I unsubscribed from MIRI's RSS feed because I found the content too technical. I imagine that that's true of most EAs. But I'm not strongly opposed to it.

According to Heap, about 1% of visitors clicked the blog links in the past month, and 41% clicked on anything. So maybe 2.5% of people who engaged with the site at all clicked on one of the blog links. I don't think it matters much what we put in there.

**Comment by peterhurford** [comment]
Fair enough. I don't think anyone has complained... and it was a reasonable ordeal to get OpenPhil up there. Fine on punting on this.
