### ISSUE TITLE
If you're logged out, then upvote, the login page appears but doesn't actually log you in.

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#8]
- If you're logged out, then upvote, the login page appears but doesn't actually log you in.

**Comment by JoshuaDavid** [comment]
It looks like it is actually logging you in, but not refreshing the page. Here are my observations:
1. Logged out
2. Viewed an article
3. Clicked the upvote button
4. Got popup "log in or register" overlay
5. Entered my username / password and hit submit
6. Overlay disappeared, UI still had the "Log In / Sign Up" button (i.e. did not show I was logged in)
7. Refreshed the page
8. UI now showed that I was logged in.

If you observe the same thing, that means all we need to do is refresh the page after the user logs in.

**Comment by tog22** [comment]
I've observed that after logging in it takes a page refresh to _show_
you're actually logged in - several times, in several other cases. So yes,
I think you could prompt a refresh - can do no harm, after all!

**Comment by peterhurford** [comment]
Should we make a PR to refresh the page then?

**Comment by peterhurford** [comment]
@JoshuaDavid Have you made any progress on this?

**Comment by RyanCarey** [comment]
Agree that this is important, and that you need to refresh to make buttons appear after being logged in after clicking upvote.

**Comment by tog22** [comment]
Are you up for having a go at this @patbl ?

**Comment by patbl** [comment]
Sure, I'll take a look at it tomorrow.

**Comment by tog22** [comment]
:raised_hands:

**Comment by patbl** [comment]
My hack of using using a query parameter doesn't get to the root cause of the bug. If you click the "Comments ([number of comments)" link in the upper right after logging in, you appear to be logged out again. But this seems like kind of a corner case, and there are probably more important things to be working on.

**Comment by tog22** [comment]
>  But this seems like kind of a corner case, and there are probably more important things to be working on.

Agree with that. :smile:

**Comment by tog22** [comment]
@patbl (and @peterhurford ), can we close this issue?

**Comment by patbl** [comment]
Yes. There's a similar bug for upvoting posts (as opposed to comments). I can't remember whether the behavior is the same as for comments, but it's pretty annoying. I'll create a separate issue for it, though.

**Comment by patbl** [comment]
Actually, the description seems to encompass upvotes of both comments and articles, so I'll reopen this.

The current behavior for articles is still broken.
1. You're logged out.
2. You click the upvote button for an article.
3. The log-in modal appears.
4. You log in.
5. The log-in modal disappears, but you still appear to be logged out.

After completing these steps, you can cycle through them indefinitely. Only doing something that requires a page load seems to fix it.

I could have a go at fixing this for real since I've worked on it already, but I don't have the best record lately. Maybe give me a week, then someone else can work on it if I haven't.

**Comment by patbl** [comment]
I guess it was fixed, but the fix hasn't been deployed. I think we should keep an issue open till the fix is deployed and we've verified that it works in production.

**Comment by tog22** [comment]
Agreed
