### ISSUE TITLE
Posts can no longer be tagged

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#85]
Tags aren't that important, but they do make it so we can mark open threads, and they could become important in the future if we want more forum categorization.

**Comment by tog22** [comment]
To be clear, I personally think this is our highest priority for forum
work, and one worth doing soon to boot. But @peterhurford and
@georgiemallett are more involved in coordinating this so can say if they
disagree!

**Comment by peterhurford** [comment]
@tog22 Marked it high priority but curious to hear more about why you think it is important.

**Comment by tog22** [comment]
Solely for making the 'open thread' link in the sidebar work. I presume
that's the most broken easily fixable part of the forum experience?

**Comment by patbl** [comment]
I removed them because they weren't being used [here](https://github.com/tricycle/eaforum/pull/49). Open threads were identified by title. I have [a pull request](https://github.com/tricycle/eaforum/pull/68/commits/c9c57d1b2d611dc9c954cb6385f34c4d873364bd) to update the title matching. (The link would point to the most recent post with "open thread" [case insensitive] in its title.)

Maybe we should bring back tags instead. It seems a little bit bad to have the tags box there when it's used only for open threads. But it's probably fine.

What do you think about tags versus titles for open threads?

**Comment by peterhurford** [comment]
It looks like https://github.com/tricycle/eaforum/pull/68/files is a fine solution for now and that we can reflect on the value of tags as a part of the general CEA-driven(?) initiative to improve the forum.

**Comment by tog22** [comment]
Oh yeah, using titles and leaving the tag capacity unenabled for now sounds
sensible. There's a CEA-driven initiative to improve the forum? I thought
we were handling it OK, but I guess something for @georgiemallett to
discuss with them!

**Comment by patbl** [comment]
I'm closing this in favor of #84.
